systems:
  basedir: "./logs"

model:
  model_name: "HexPlane"
  N_voxel_init: 262144
  time_grid_init: 16
  time_grid_final: 24
  upsampling_type: "unaligned"
  upsample_list: [3000, 6000, 9000]
  update_emptymask_list: [4000, 8000, 10000]
  fusion_one: "multiply"
  fusion_two: "multiply"
  init_scale: 0.9
  init_shift: 0.5
  density_dim: 8
  DensityMode: "general_MLP"
  compression:
    enable: true
    type: "mbt2018"
    latent_dim: 128
    lr_codec_net: 1e-4
    lr_codec_aux: 1e-3
    app_rate_weight: 1e-5
    app_reg_weight: 0.0
    codec_warmup: 1000

data:
  datadir: "/project/jacobcha/nk643/HexPlane/dataset/dnerf/lego"
  scene_bbox_min: [-1.5, -1.5, -1.5]

optim:
  n_iters: 2500
  lr_decay_type: "exp"
  lr_density_grid: 0.02
  lr_app_grid: 0.02
  lr_density_nn: 0.001
  lr_app_nn: 0.001
  beta1: 0.9
  beta2: 0.99

render_test: True
render_path: True
#expname: dnerf_general_lego
expname: dnerf_general_lego_compressai_mbt2018_mean